name: 'Terraform Azure CI/CD'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      env:
        TF_VAR_subscription_id: 9cd57d91-e05d-4f9f-a49c-2a59561e7a33
        TF_VAR_admin_password: ${{ secrets.TF_ADMIN_PASSWORD }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
      env:
        TF_VAR_subscription_id: 9cd57d91-e05d-4f9f-a49c-2a59561e7a33
        TF_VAR_admin_password: ${{ secrets.TF_ADMIN_PASSWORD }}
